# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "[âœ](bold green)"     # The "symbol" segment is being set to "âœ"
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
use_symbol_for_status = true

# Avoid cluttering the terminal with useless time measurements
[cmd_duration]
disabled = true

# Show Username
[username]
disabled = false
show_always = true
style_user = "bright-blue bold"
style_root = "red bold"
format = "[îˆ® $user]($style) [Î»](fg:#FF7700 bold) "

# Avoid line break
[line_break]
disabled = true

# Show git status
[git_status]
ahead = "â‡¡ ${count} "
staged = '[++\($count\)](green)'
diverged = "â‡•â‡¡ ${ahead_count} â‡£ ${behind_count}"
behind = "â‡£ ${count} "

# Show git states
[git_state]
cherry_pick = "[ğŸ’ PICKING](bold red)"

# Show exit code status
[status]
disabled = false
format = " [$status]($style) "
